# Generated by Django 5.0.4 on 2024-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_junior_number_junior_tg_id_mentor_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='junior',
            old_name='image_url',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='image_url',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='type',
            field=models.CharField(choices=[(1, 'Stajirovka'), (2, 'Ishlar'), (3, 'Loyihalar')], default=0, max_length=15),
            preserve_default=False,
        ),
    ]
