# Generated by Django 5.0.4 on 2024-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_image_url_junior_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
