# Generated by Django 5.0.4 on 2024-04-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.IntegerField(choices=[(1, 'Stajirovka'), (2, 'Ishlar'), (3, 'Loyihalar')], max_length=15),
        ),
    ]
