# Generated by Django 5.0.4 on 2024-04-28 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_vacancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.field'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.IntegerField(choices=[(1, 'Stajirovka'), (2, 'Ishlar'), (3, 'Loyihalar')]),
        ),
    ]
