# Generated by Django 5.0.4 on 2024-04-28 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_event_field_alter_vacancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.field'),
        ),
    ]
