# Generated by Django 5.0.4 on 2024-04-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_article_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
